[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
finalwhistle = "3twLVgxWB3fF6EkHGoNzH4ax8sH82fz2KZjgjwg4y7fs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec vitest run"
